### ISSUE TITLE
/bin/sh: tiktok-scraper: command not found

### ISSUE THREAD

**Issue by WilliamButtlickerIII** [bellingcat/tiktok-hashtag-analysis#11]
After trying to execute a search 

> python3 run_downloader.py -t #hashtag -p

it returned 

> /bin/sh: tiktok-scraper: command not found. 

Wondering how I can troubleshoot it.

**Comment by binlabs** [comment]
It looks like you accidentally skipped the first three [prerequisites for installing](https://github.com/drawrowfly/tiktok-scraper#installation) and running this tool.

[tiktok-scraper](https://github.com/drawrowfly/tiktok-scraper#installation) is a CLI built in Node.js. In order to install it, you'll need to first install Node.js. Once you have Node.js installed, you can install the scraper by running `npm i -g tiktok-scraper`

You may need to restart your terminal/command prompt after installing tiktok-scraper before trying to run your hashtag search.
