### ISSUE TITLE
npm i -g tiktok-scraper not working/supported

### ISSUE THREAD

**Issue by Gsammy** [bellingcat/tiktok-hashtag-analysis#15]
I have been following the step-by-step instructions on the Bellingcat site. All the steps had worked so far except n 16, but I was still able to get the correct version number displayed through sudo n 16. However, when I enter npm i -g tiktok-scraper, it states that it cannot run the program because Request has been deprecated. When I tried following the directions on the GitHub page, I got this error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'. 
Is there some way around this issue?

For context, I have a Mac book Air and had Python 3 installed before starting the tutorial. I have no real coding/computer science experience, so I don't really know how to troubleshoot. Thanks!

**Comment by binlabs** [comment]
> When I tried following the directions on the GitHub page, I got this error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'.

Was this error produced when trying to run the `pip install -r requirements.txt` command?

If so, you'll want to make sure that you're doing so from the root folder of this project, since that is where the requirements.txt file is located.

In your terminal or command prompt, use the `cd` command to change directories to where you have cloned this repo. For example, `cd ./tiktok-hashtag-analysis`

Let me know if you need help figuring out where you cloned the repo to, and I can give you some more specific info on how to use `cd` to change to that directory.

**Comment by trislee** [comment]
Switched to a non-broken, Python-language scraper. This problem should be addressed in the most recent version of the tool. Let me know if you're still experiencing problems running the tool.
